env:
  node: true
  browser: true
  commonjs: true
  es6: true
  es2021: true
extends: 
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
plugins: [prettier]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - tab
    - { "SwitchCase": 1 }
  quotes:
    - error
    - single
  semi:
    - error
    - always
  linebreak-style: off
  # brace-style: [warn, stroustrup, { allowSingleLine: true }]
  no-tabs: off
  # max-len: [error, { code: 120, ignoreUrls: true }]
  # comma-dangle: [error, always-multiline]
  no-underscore-dangle: [error, { allowAfterThis: true, allowAfterSuper: true }]
  # no-plusplus: [error, { allowForLoopAfterthoughts: true }]
  object-curly-spacing: [error, always]
  no-console: off
  arrow-parens: [error, as-needed]
  no-unused-vars: warn
  prefer-template: warn